### ISSUE TITLE
DNN library initialization failed

### ISSUE THREAD

**Issue by zhouyium** [mdsunivie/deeperwin#7]
I use conda to mange the package. The following is the installation.
1. Create a conda enviroment
    conda create -n deeperwin python=3.8
2. Activate the enviroment
    conda activate deeperwin
(deeperwin) yzhou@Moss:~/base/. so the deeperwin is activated.
3. Clone the source code
   git clone https://github.com/mdsunivie/deeperwin.git
4. Install deeperwin
    cd deeperwin
    pip install -e .
5. After installation, I check the jax is using GPU
    `python
Python 3.8.16 (default, Mar  2 2023, 03:21:46)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
>>> jax.local_device_count()
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
1`
So here is no GPU found, but I do have a A100 GPU.
6. Upgrade jax to gpu version and check
   `$ pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
 python
Python 3.8.16 (default, Mar  2 2023, 03:21:46)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
>>> jax.local_device_count()
1
>>> print(jax.devices()[0])
gpu:0`
   So the GPU is ready.
7. Run the sample_configs/config_basic.yml
   Something wrong. the information is 
`$ deeperwin run sample_configs/config_basic.yml
Traceback (most recent call last):
  File "/home/yzhou/base/anaconda3/envs/deeperwin/bin/deeperwin", line 33, in <module>
    sys.exit(load_entry_point('deeperwin', 'console_scripts', 'deeperwin')())
  File "/media/hdd/yzhou/deeperwin/src/deeperwin/cli.py", line 52, in main
    process_molecule(args.config_file)
  File "/media/hdd/yzhou/deeperwin/src/deeperwin/process_molecule.py", line 14, in process_molecule
    config: Configuration = Configuration.parse_obj(raw_config)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1102, in pydantic.main.validate_model
  File "/media/hdd/yzhou/deeperwin/src/deeperwin/configuration.py", line 1164, in no_reuse_while_shared
    if (values['optimization'].shared_optimization is not None) and (values['reuse'] is not None):
KeyError: 'optimization'
`
8 Run the sample_configs/config_minimal.yml
  Here is the wrong information:
`$ deeperwin run sample_configs/config_minimal.yml
2023-05-22 12:48:56.136608: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:407] There was an error before creating cudnn handle (302): cudaGetErrorName symbol not found. : cudaGetErrorString symbol not found.
Traceback (most recent call last):
  File "/home/yzhou/base/anaconda3/envs/deeperwin/bin/deeperwin", line 33, in <module>
    sys.exit(load_entry_point('deeperwin', 'console_scripts', 'deeperwin')())
  File "/media/hdd/yzhou/deeperwin/src/deeperwin/cli.py", line 52, in main
    process_molecule(args.config_file)
  File "/media/hdd/yzhou/deeperwin/src/deeperwin/process_molecule.py", line 36, in process_molecule
    from deeperwin.optimization import optimize_wavefunction, evaluate_wavefunction, pretrain_orbitals
  File "/media/hdd/yzhou/deeperwin/src/deeperwin/optimization.py", line 9, in <module>
    from deeperwin.evaluation import evaluate_wavefunction
  File "/media/hdd/yzhou/deeperwin/src/deeperwin/evaluation.py", line 8, in <module>
    from deeperwin.loggers import DataLogger, WavefunctionLogger
  File "/media/hdd/yzhou/deeperwin/src/deeperwin/loggers.py", line 18, in <module>
    from deeperwin.checkpoints import save_run, RunData
  File "/media/hdd/yzhou/deeperwin/src/deeperwin/checkpoints.py", line 6, in <module>
    from deeperwin.mcmc import MCMCState
  File "/media/hdd/yzhou/deeperwin/src/deeperwin/mcmc.py", line 17, in <module>
    class MCMCState:
  File "/media/hdd/yzhou/deeperwin/src/deeperwin/mcmc.py", line 27, in MCMCState
    stepsize: jnp.array = jnp.array(1e-2)
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 2022, in array
    out_array: Array = lax_internal._convert_element_type(out, dtype, weak_type=weak_type)
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 549, in _convert_element_type
    return convert_element_type_p.bind(operand, new_dtype=new_dtype,
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/core.py", line 380, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/dispatch.py", line 131, in apply_primitive
    compiled_fun = xla_primitive_callable(
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/util.py", line 284, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/util.py", line 277, in cached
    return f(*args, **kwargs)
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/dispatch.py", line 222, in xla_primitive_callable
    compiled = _xla_callable_uncached(
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/dispatch.py", line 252, in _xla_callable_uncached
    return computation.compile().unsafe_call
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2313, in compile
    executable = UnloadedMeshExecutable.from_hlo(
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2633, in from_hlo
    xla_executable, compile_options = _cached_compilation(
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2551, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/dispatch.py", line 495, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/yzhou/base/anaconda3/envs/deeperwin/lib/python3.8/site-packages/jax/_src/dispatch.py", line 463, in backend_compile
    return backend.compile(built_c, compile_options=options)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
`
It seems the DNN is not available.

**Comment by zhouyium** [comment]
Dear all:
   I have fixed this problem. just upgrade jax to cuda12. 
pip install --upgrade "jax[cuda12_local]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
Thanks all.
